name: top_mouse_tracker_env
channels:
  - conda-forge
dependencies:
  - numpy
  - scipy
  - matplotlib
  - moviepy
  - opencv >= 3.1.0,<= 3.4.9
  - scikit-image
  - tqdm
  - pandas
  - natsort
#  - ffmpeg
