name: tomtop
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - numpy
  - matplotlib
  - pandas
  - natsort
  - configobj
  - scipy
  - psutil
  - pywin32-ctypes
  - pyautogui
  - opencv
  - moviepy
  - sk-video